
database:
  # Can be "h2", "sqlite", or "mariadb"
  driver: h2

  # H2 and SQLite
  # Relative path to the database file
  path: mcelo-db

  # MariaDB
  host: localhost
  port: 3306
  database: database
  username: user
  password: password
  ssl: false
  sslVerify: true

tau: 0.75
initial-volatility: 0.06
initial-rating: 1500
initial-rd: 350
glixare-scale: 25000

messages:
  player-elo: "Your rating is <glixare> (raw: <rating>±<rd>)."
  player-elo-other: "<player>'s rating is <glixare> (raw: <rating>±<rd>)."
  player-not-found: "Player not found."
