name: MCElo
main: "me.badaimweeb.mcelo.MCElo"

version: ${version}
author: BadAimWeeb

api-version: "1.13"
description: "General-purpose Glicko-2 Elo calulator/tracker for Spigot/Paper"

commands:
  eloadmin:
    description: "Admin command for MCElo"
    permission: "mcelo.eloadmin"
    usage: /eloadmin
  elo:
    description: "Get your rating"
    usage: /elo [player]
    permission: "mcelo.elo"

permissions:
  mcelo.*:
    description: "Ability to use all MCElo commands"
    children:
      - mcelo.eloadmin
      - mcelo.elo
    op: true

  mcelo.eloadmin:
    description: "Ability to use the MCElo admin command"
    op: true

  mcelo.elo:
    description: "Ability to use the MCElo elo command"
    default: true
